# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"



[params]
    author = "Ismail KABOUBI"
    description = "Ismail KABOUBI's resume."

    primaryColor = "#54B99F"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Ismail KABOUBI"
        tagline = "🇹🇳🚀 2x ⎈ Kubernetes Certified Engineer | Freelance SRE 🚀🇹🇳"
        avatar = "avatar.png"


    [params.contact]
        enable = true
        location = "Paris FR"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+33 6 63 01 40 09"
        text = "+33 6 63 01 40 09"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ikaboubi@gmail.com"
        text = "ikaboubi@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://me.smileisak.com"
        text = "me.smileisak.com"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Kubernetes/Containers"
        [[params.skills.list.items]]
        details = "Python/Go"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement Kubernetes Platforms"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    
    [params.education]
        enable = true
        [[params.education.list]]
        degree = "National Engineering Degree in Computer Networks and Telecomunications"
        university = "INSAT, National Institute of Applied Sciences and Technology."
        dates = "October - 2015"
        [[params.education.list]]
        degree = "Preparatory Studies Entrance to the Engineering Program"
        university = "INSAT, National Institute of Applied Sciences and Technology."
        dates = "2010 - 2012"
        [[params.education.list]]
        degree = "Bachelor on Computer Science- with honors"
        university = "Tunis - Alaoui High School"
        dates = "2009 - 2010"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Certified Kubernetes Administrator"
        body = "Among first pepole taking this certification"
        date = "Dec 2017"
        img = "logo_cka.png" 
        [[params.awards.list]]
        name = "Certified Kubernetes Application Developer"
        body = "Taken as beta tester"
        date = "May 2018"
        img  = "logo_ckad.png" 

        [[params.awards.list]]
        name = "Docker Technical Sales Professional"
        body = "Technical Sales Professional"
        date = "May 2018"
        img  = "docker.png" 

        [[params.awards.list]]
        name = "LPIC1"
        body = "Linux Professional Institute Certification - 1"
        date = "Mar 2013"
        img  = "lpic1.png" 


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Arabic"
        level = "Native"
        [[params.languages.list]]
        name = "French"
        level = "Bilingual"
        [[params.languages.list]]
        name = "English"
        level = "Professional"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Handball"
        [[params.interests.list]]
        name = "Craftsmanship"

    [params.summary]
        enable = true
        text = """
Today working as Self Employed DevOps/SRE/Backend Engineer. Certified Kubernetes Administrator and Application Developer, working on Kubernetes since the version 1.1 in Sep 2015. Experienced also with cloud platforms like Amazon Web Services or Google Cloud Platform. Putting in place platforms for automating deployment, scaling, and operations of application containers across clusters of hosts using Kubernetes / Docker and bunch of other DevOps tools.
The second important part of my core business today is to deliver multi-tenant application (REST API) that can handle a big number of customers with the same code base, with some Design patterns, and best practices approaches.
I'm also a Lazy Contributor on Kubernetes Eco-System wanting more time and effort on Open Source Contribution specifically on  Kubernetes World.
"""
    
    
    [params.experience]
        enable = true
        [[params.experience.list]]
            title = "Senior Software Reability Engineer / SRE (Freelance)"
            dates = "Nov 2018 - Present"
            company = "Renault AITS"
            details = "In a few years, Renault AITS will stop its 2 Datacenters. Strategy is changed to public cloud first approch. During this exp i’ve touched all kind of public/private clouds, technologies and programming languages. The context of this exp is:"
            
            [[params.experience.list.items]]
            details = "Driving migration process to public cloud providers for more than ~1000 applications."
            [[params.experience.list.items]]
            details = "Proposing and contributing on production ready multitenant Kubernetes architectures."
            [[params.experience.list.items]]
            details = "Assuring that all applications that will migrate respects Cloud Native approach."
            [[params.experience.list.items]]
            details = "Design and develop Kubernetes Operators to manage Custom Resource Definitions to provision multi-tenant environments"

            [[params.experience.list.tools.items]]
            name = "Google Cloud Platform"
            link = "https://cloud.google.com/kubernetes-engine?hl=fr"
            [[params.experience.list.tools.items]]
            name = "GKE"
            link = "https://cloud.google.com/kubernetes-engine?hl=fr"
            [[params.experience.list.tools.items]]
            name = "ArgoCD"
            link = "https://argoproj.github.io/argo-cd/"
            [[params.experience.list.tools.items]]
            name = "Kopf"
            link = "https://kopf.readthedocs.io/en/stable/"
            [[params.experience.list.tools.items]]
            name = "Cert Manager"
            link = "https://cert-manager.io/docs/"
            [[params.experience.list.tools.items]]
            name = "CleanUp Operator"
            link = "https://github.com/lwolf/kube-cleanup-operator"
            [[params.experience.list.tools.items]]
            name = "Config Connector"
            link = "https://cloud.google.com/config-connector/docs/overview?hl=en"
            [[params.experience.list.tools.items]]
            name = "Nginx Ingress Controller"
            link = "https://kubernetes.github.io/ingress-nginx/"
            [[params.experience.list.tools.items]]
            name = "OPA GateKeeper"
            link = "https://www.openpolicyagent.org/"
            [[params.experience.list.tools.items]]
            name = "KubeD"
            link = "https://appscode.com/products/kubed/"
            [[params.experience.list.tools.items]]
            name = "Logging Operator"
            link = "https://banzaicloud.com/products/logging-operator/"
            [[params.experience.list.tools.items]]
            name = "Prometheus Operator"
            link = "https://github.com/coreos/prometheus-operator"
            [[params.experience.list.tools.items]]
            name = "Grafana"
            link = "https://grafana.com/"
            [[params.experience.list.tools.items]]
            name = "Velero"
            link = "https://velero.io/"
            [[params.experience.list.tools.items]]
            name = "Terraform"
            link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
            name = "GitlabCI"
            link = "https://gitlab.com/"
        
        
        [[params.experience.list]]
            title = "Kubernetes Specialist (Smile)"
            dates = "Sep 2018 - Nov 2018"
            company = "Renault AITS"
            details = "During this exp i've participated to studies of choosing the right solution for Renault AITS to deliver the same Kubernetes service level as public cloud providers. We have PoCed during this exercice:"
            [[params.experience.list.items]]
                details = "Pivotal Kubernetes Service"
            [[params.experience.list.items]]
                details = "Mesosphere DC OS"
            [[params.experience.list.items]]
                details = "Platform9"

            [[params.experience.list.tools.items]]
                name = "Terraform"
                link = "https://terraform.io/"

            [[params.experience.list.tools.items]]
                name = "GitlabCI"
                link = "https://gitlab.com/"
            [[params.experience.list.tools.items]]
                name = "RedHat OpenStack"
                link = "https://www.redhat.com/fr/technologies/linux-platforms/openstack-platform"
            [[params.experience.list.tools.items]]
                name = "Kubernetes"
                link = "https://kubernetes.io"
            

        [[params.experience.list]]
            title = "Senior Software Reability Engineer / SRE (Smile)"
            dates = "Fev 2018 - Sep 2018"
            company = "Renault AITS"
            details = "SUEZ supports city development around the world with through its historical activities, which are water and waste management services. SUEZ Smart Solutions, a subsidiary of the Group, provides intelligent solutions and expertise to support regions in their environmental and digital transformation. During this experience, i’ve the responsability as an SRE of these two Plateforms: "
            [[params.experience.list.items]]
                details = "DigitalCity Saint Etienne: integrates data collection solutions (smart meters, sensors and probes) to provide digital models and real-time applications, thus moving towards rational use of resources and resilience in times of crisis. It consit of OpenAPI Platform that expose public API to end-users to create Apps for Saint Etienne Smart City."
            [[params.experience.list.items]]
                details = "ON’connect coach: This solution is intended to support users in optimizing their consumption, in particular of domestic hot water"

            [[params.experience.list.tools.items]]
                name = "Kubernetes"
                link = "https://kubernetes.io"
            [[params.experience.list.tools.items]]
                name = "Azure"
                link = "https://kubernetes.io"
            [[params.experience.list.tools.items]]
            name = "Prometheus Operator"
            link = "https://github.com/coreos/prometheus-operator"
            [[params.experience.list.tools.items]]
            name = "Grafana"
            link = "https://grafana.com/"
            
            [[params.experience.list.tools.items]]
                name = "Kafka"
                link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
                name = "MongoDB"
                link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
                name = "ElasticSearch"
                link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
                name = "InfluxDB"
                link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
                name = "Cassandra"
                link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
                name = "Percona MYSQL"
                link = "https://terraform.io/"
            [[params.experience.list.tools.items]]
                name = "Kong API Gateway"
                link = "https://konghq.com/kong/"

    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/smileisak"
        title = "smileisak"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/ismail-kaboubi"
        title = "ismail-kaboubi"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/smileisak"
        title = "@smileisak"





